### ISSUE TITLE
UnboundLocalError with -Si as only arguments

### ISSUE THREAD

**Issue by AladW** [Kwpolska/pkgbuilder#51]
```
$ pkgbuilder -Si 
Traceback (most recent call last):
  File "/usr/bin/pkgbuilder", line 11, in <module>
    load_entry_point('pkgbuilder==4.2.10', 'console_scripts', 'pkgbuilder')()
  File "/usr/lib/python3.6/site-packages/pkgbuilder/__main__.py", line 227, in main
    exit(qs)
UnboundLocalError: local variable 'qs' referenced before assignment
```
```
$ pkgbuilder --version
PKGBUILDer v4.2.10
```

**Comment by Kwpolska** [comment]
That was a minor oversight, thanks for reporting. (It’s not worth it to make a release right now, so just avoid running `-Si` with no arguments.)
