### ISSUE TITLE
Error with python 3.9

### ISSUE THREAD

**Issue by elizabeth-dev** [Kwpolska/pkgbuilder#65]
Updating to python 3.9.0-1 from the Arch Linux extra repo with pkgbuilder 4.3.0-2 gives the following error: 

```
Traceback (most recent call last):
  File "/usr/bin/pkgbuilder", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pkgbuilder==4.3.0' distribution was not found and is required by the application
```

**Comment by Kwpolska** [comment]
Thanks for reporting. Upgrading Python major versions requires rebuilding all Python packages to put them in their new places. I rebuilt the `pkgbuilder-repo` package, `pacman -Syu` should fix it if you’re using that repo. If you installed PKGBUILDer directly from the AUR, you will need to rebuild/update the package manually.

**Comment by elizabeth-dev** [comment]
@Kwpolska Working perfectly now, thanks!
